

public class Main {

    int g =a;
    static int a;








    public static void main(String[] args) {
        //Begin Scope
        Scope s = new Scope();
        s.accessingLocalAndGlobal();
        // End Scope

        //BeginSwitch
        Switch switchTypes = new Switch();
        switchTypes.switchStatements();
        Switch switchExpression = new Switch();
        switchExpression.switchExpression();
        //EndSwitch

        //BeginVariableArgumentsAndStrings

        VariableArgumentsAndStrings vS = new VariableArgumentsAndStrings();
        vS.usingStrings();
        vS.varArgs(new int[]{1, 2, 3});
        vS.varArgs("Shuja", new int[]{3, 4, 5});
        //EndVariableArgumentsAndStrings


        //BeginRecord

        Records records = new Records(5,"recordAreImmutable", 3);
        //Accessing Record using autogenerated getters
        System.out.println(records.intRecord());
        records.myExtensionMethod();
        //EndRecord


        //BeginAbstractClasses
        //Implicit Upcasting makes code more generic and flexible
        AbstractClasses aC = new AbstractClassesChildLv2();
        aC.A();
        aC.B();
        //EndAbstractClasses


        //BeginInterface
         System.out.println("Accessing Interface1 data member using name as its implicitly pubic, static and final" + Interfaces1.MYVAR);
         Interfaces1.interfaceMethodPublic();
         InterfacesClass1Lv1 icL1 = new InterfacesClass1Lv1();
         icL1.newlyAdded();
         icL1.move();
        //EndInterface


        //BeginConstructorsAndInheritance

        ConstructorsAndInheritance caI = new ConstructorsAndInheritanceChild1Lv1();
        caI.A();

        //Limiting inheritance using sealed, non-sealed and final

        //EndConstructorsAndInheritance




        












        System.out.println("Hello world!");
    }
}